baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'BC & NAV notes'
theme = 'hugo-theme-relearn'
enableGitInfo = true
[params]
  collapsibleMenu = true
  alwaysopen = true
  themeVariant = ['zen-dark', 'zen-light']
  externalLinkTarget = '_blank'
[caches]
  [caches.images]
    dir = ':cacheDir/images'